services:
  wandshopservice:
    image: ${DOCKER_REGISTRY-}wandshopservice
    build:
      context: .
      dockerfile: WandShopService/Dockerfile
    depends_on:
      - db
    environment:
      - CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
    ports:
      - "5000:5000"
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_wands_data:/var/opt/mssql

volumes:
  mssql_wands_data:
